name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd client && npm install

      - name: Build
        run: cd client && npm run build

      - name: Set credentials
        run: git config --global user.email "justin.b.cortez@gmail.com" && git config --global user.name "Justin Cortez"

      - name: Create build branch
        run: git checkout -b build

      - name: Fast forward
        run: git config pull.ff only

      - name: Pull from build
        run: git pull origin build

      - name: Add changes
        run: git add .

      - name: Force add dist
        run: git add -f client/dist

      - name: Commit changes
        run: git commit -m "Build"



      - name: Push to Another Branch
        run: git push origin build
